
default: &default
  adapter: postgresql
  encoding: unicode
  user: rodrigo
  password: 12345678
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: naveg_mvp_development

test:
  <<: *default
  database: naveg_mvp_test


production:
  <<: *default
  database: naveg_mvp_production
  username: naveg_mvp
  password: <%= ENV['NAVEG_MVP_DATABASE_PASSWORD'] %>
